// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameArticle = "articles"

// Article mapped from table <articles>
type Article struct {
	ID          int32     `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	IDAuthor    int32     `gorm:"column:id_author;type:integer;not null" json:"id_author"`
	Slug        string    `gorm:"column:slug;type:text;not null" json:"slug"`
	Title       string    `gorm:"column:title;type:text;not null" json:"title"`
	Description string    `gorm:"column:description;type:text" json:"description"`
	Body        string    `gorm:"column:body;type:text;not null" json:"body"`
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Article's table name
func (*Article) TableName() string {
	return TableNameArticle
}
