// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUserLike = "user_likes"

// UserLike mapped from table <user_likes>
type UserLike struct {
	IDUser    int32 `gorm:"column:id_user;type:integer;primaryKey" json:"id_user"`
	IDArticle int32 `gorm:"column:id_article;type:integer;primaryKey" json:"id_article"`
}

// TableName UserLike's table name
func (*UserLike) TableName() string {
	return TableNameUserLike
}
