// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        int32     `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	Username  string    `gorm:"column:username;type:text;not null" json:"username"`
	Email     string    `gorm:"column:email;type:text;not null" json:"email"`
	Password  string    `gorm:"column:password;type:text;not null" json:"password"`
	Bio       string    `gorm:"column:bio;type:text" json:"bio"`
	Image     string    `gorm:"column:image;type:text" json:"image"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
